<center>
<img src= https://a-z-animals.com/media/2021/07/Fluffiest-Animals_-Giant-Panda.jpg>
</center>

# Are they Dangerous???
## Find Out [🐼](https://a-z-animals.com/blog/are-pandas-dangerous/)

<center>
<img src= https://trainingthestreet.com/nitropack_static/IBHPHnjyQTGHxBaTMwYZqDYsplzhVmvX/assets/images/optimized/rev-3531652/trainingthestreet.com/wp-content/uploads/2025/06/Pandas_logo.svg-1024x414.png>
</center>

# **Introduction to Pandas**
# Pandas = Data manipulation library


# Key Structures 
   - # Series (1D array) A one-dimensional labelled array (like a column in a spreadsheet)
   - # DataFrame (2D array) A two-dimensional labelled data structure (like a table with rows and columns)

In [1]:
# pip install pandas

In [2]:
import pandas as pd

In [ ]:
nineToone = pd.Series([9,8,7,6,5,4,3,2,1])
serisedata

In [7]:
pd.Series([1,2,3,4,5,6,7,8]) # This is a Series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [8]:
data = {'Name': ['Raj', 'Monica'], 'Age': [25, 30]}
pd.DataFrame(data) # This is DataFrame

     Name  Age
0     Raj   25
1  Monica   30

In [9]:
df = pd.DataFrame({"S_name":["Akash","Puja","Lina","Rawina"],
    "S_ID":["2026cs001","2026cs002","2026cs003","2026cs004"],
    "S_email":["akash.in@gmail.com","puja@gmail.com","lina@gmail.com","rawina@gmail.com"]})

In [10]:
students = {
    "S_name":["Akash","Puja","Lina","aman"],
    "S_ID":["2026cs001","2026cs002","2026cs003","2026cs004"],
    "S_email":["akash@gmail.com","puja@gmail.com","lina@gmail.com","aman@gmail.com"]}
students['S_name']

['Akash', 'Puja', 'Lina', 'aman']

In [11]:
df = pd.DataFrame(students)

df # we get the entire data
#print(df.S_name, "\n", df.S_ID)
df[['S_email','S_ID']]

           S_email       S_ID
0  akash@gmail.com  2026cs001
1   puja@gmail.com  2026cs002
2   lina@gmail.com  2026cs003
3   aman@gmail.com  2026cs004

In [12]:
type(df.S_email)
#type(df['S_email'])

pandas.Series

In [14]:
df = pd.read_csv('survey_results_public.csv')
df
df.shape
#df.info()
#df.head()
#df.tail()
#pd.set_option('display.max_rows',40)
#pd.set_option('display.max_column',3)

(88883, 85)

In [15]:
pd.set_option('display.max_rows',10)
pd.set_option('display.max_colum',10)

In [16]:
df.columns # shows all the columns in a data set
df[['Hobbyist', 'Student']]

      Hobbyist         Student
0          Yes              No
1           No  Yes, full-time
2          Yes              No
3           No              No
4          Yes              No
...        ...             ...
88878      Yes              No
88879       No             NaN
88880       No             NaN
88881       No             NaN
88882      Yes  Yes, full-time

[88883 rows x 2 columns]

In [17]:
#df[['Country','Student']]
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

In [18]:
df['Age'].value_counts() # categorial count in age column

Age
25.0    4669
24.0    4428
27.0    4418
26.0    4397
28.0    4387
        ...
37.3       1
33.5       1
53.8       1
31.4       1
87.0       1
Name: count, Length: 126, dtype: int64

# **Loc vs iloc**
# What is .loc[]?
 - # Used for label-based data selection
 - # We select data by row or column names

In [19]:
# loc[] structure is as (df.loc[rwo_label, column_label])
df.loc[2,['Country','Age', 'LanguageWorkedWith']]
#df.columns

Country               Thailand
Age                       28.0
LanguageWorkedWith    HTML/CSS
Name: 2, dtype: object

# Why we use .loc[]?
 - # Easy to use when working with named indices or column headers
 - # Supports label slicing and conditional access

In [20]:
df.loc[df['Age']>30]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,...,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,...,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
13,14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,...,Straight / Heterosexual,White or of European descent,No,Too short,Easy
18,19,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,...,Straight / Heterosexual,Hispanic or Latino/Latina,Yes,Too long,Easy
19,20,"I am not primarily a developer, but I write co...",No,Never,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...
88859,85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...",...,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88863,85961,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,...,Gay or Lesbian,White or of European descent,No,Appropriate in length,Difficult
88865,86566,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",...,NaN,White or of European descent,No,Appropriate in length,Easy
88870,87352,NaN,Yes,Less than once per year,NaN,...,NaN,NaN,No,NaN,NaN
88876,88212,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

# What is .iloc[]?
 - # Used for position-based selection
 - # We select data by integer position (like list indexes)

In [21]:
# structre of .iloc[] (df.iloc[row_index, column_index])
df.iloc[0,1] # This shows the first row, second column value

'I am a student who is learning to code'

# Why we use .iloc[]?
 - # Precise and consistent with zero-based indexing
 - # Useful when labels are unknown or sequential

In [459]:
df.iloc[0:15] # showe the first 3 rows

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,...,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,...,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,...,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,...,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,...,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...
10,11,I code primarily as a hobby,Yes,Once a month or more often,The quality of OSS and closed source software ...,...,Bisexual;Gay or Lesbian;Straight / Heterosexual,Black or of African descent;East Asian;Hispani...,No,Appropriate in length,Easy
11,12,I am a student who is learning to code,No,Never,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",...,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
13,14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,...,Straight / Heterosexual,White or of European descent,No,Too short,Easy
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",...,NaN,NaN,Yes,Too long,Neither easy nor difficult

In [457]:
df.loc[[0]] # show first row
df.loc[[0,2]] # first row and third row
df.loc[[0,2], 'Country'] # [[r,r],c]
df.loc[1:10, 'MainBranch':'Hobbyist']

                                           MainBranch Hobbyist
1              I am a student who is learning to code       No
2   I am not primarily a developer, but I write co...      Yes
3                      I am a developer by profession       No
4                      I am a developer by profession      Yes
5   I am not primarily a developer, but I write co...      Yes
6                      I am a developer by profession       No
7                         I code primarily as a hobby      Yes
8                      I am a developer by profession      Yes
9                      I am a developer by profession      Yes
10                        I code primarily as a hobby      Yes

# **Changing index**

In [22]:
students = {
    "S_name":["Akash","Puja","Lina","Rawina"],
    "S_ID":["2026cs001","2026cs002","2026cs003","2026cs004"],
    "S_email":["akash.in@gmail.com","puja@gmail.com","lina@gmail.com","rawina@gmail.com"]}
sdf = pd.DataFrame(students)

In [23]:
sdf.index # to check the index in the sdf dataframe

RangeIndex(start=0, stop=4, step=1)

# **Point** Make sure that the column you want to change to an index has unique values

In [24]:
sdf.set_index('S_ID') # this will change the index, but it won't be permanently applied

           S_name             S_email
S_ID
2026cs001   Akash  akash.in@gmail.com
2026cs002    Puja      puja@gmail.com
2026cs003    Lina      lina@gmail.com
2026cs004  Rawina    rawina@gmail.com

In [25]:
sdf.set_index('S_ID', inplace=True) # using inplace = True the assigned column will be permenantly converted to index

In [26]:
sdf.loc['2026cs001'] # This will retrieve the record for the student with the given id

S_name                  Akash
S_email    akash.in@gmail.com
Name: 2026cs001, dtype: str

In [27]:
sdf.iloc[0] # index based retrival while .loc[] uses label based retrival

S_name                  Akash
S_email    akash.in@gmail.com
Name: 2026cs001, dtype: str

In [28]:
sdf.reset_index(inplace=True) # this will reset the index to its original form

In [29]:
sdf

        S_ID  S_name             S_email
0  2026cs001   Akash  akash.in@gmail.com
1  2026cs002    Puja      puja@gmail.com
2  2026cs003    Lina      lina@gmail.com
3  2026cs004  Rawina    rawina@gmail.com

# **Sorting Index**

In [30]:
sdf.sort_index() #  by default, the order of the index is ascending

        S_ID  S_name             S_email
0  2026cs001   Akash  akash.in@gmail.com
1  2026cs002    Puja      puja@gmail.com
2  2026cs003    Lina      lina@gmail.com
3  2026cs004  Rawina    rawina@gmail.com

In [31]:
sdf.sort_index(ascending=False) # Assigning False boolean to it will reverse the order

        S_ID  S_name             S_email
3  2026cs004  Rawina    rawina@gmail.com
2  2026cs003    Lina      lina@gmail.com
1  2026cs002    Puja      puja@gmail.com
0  2026cs001   Akash  akash.in@gmail.com